# Assets:
SPRITESHEET_PATH = "./Eco/spritesheet/"
LEVELS_PATH = "./Eco/"

# Window settings
WINDOW_WIDTH, WINDOW_HEIGHT = 800, 400

TILESIZE = 16

GRAVITY = 0.6

SPEED_HERO = 4
ANIMSPEED_HERO_DEFAULT = 0.25
ANIMSPEED_HERO_IDLE = 0.1

SPEED_BEE = 2
ANIMSPEED_BEE = 0.2
ANIMSPEED_BEE_ATTACK = 0.5
